var annotated =
[
    [ "chunk_count_u", "unionchunk__count__u.html", "unionchunk__count__u" ],
    [ "chunk_gap_ms_u", "unionchunk__gap__ms__u.html", "unionchunk__gap__ms__u" ],
    [ "chunk_size_ms_u", "unionchunk__size__ms__u.html", "unionchunk__size__ms__u" ],
    [ "cleon_gps_data_u", "unioncleon__gps__data__u.html", "unioncleon__gps__data__u" ],
    [ "cleon_header_s", "structcleon__header__s.html", "structcleon__header__s" ],
    [ "cleon_header_u", "unioncleon__header__u.html", "unioncleon__header__u" ],
    [ "cleon_sensor_data_u", "unioncleon__sensor__data__u.html", "unioncleon__sensor__data__u" ],
    [ "DIR", "struct_d_i_r.html", "struct_d_i_r" ],
    [ "FATFS", "struct_f_a_t_f_s.html", "struct_f_a_t_f_s" ],
    [ "FIL", "struct_f_i_l.html", "struct_f_i_l" ],
    [ "FILINFO", "struct_f_i_l_i_n_f_o.html", "struct_f_i_l_i_n_f_o" ],
    [ "gps_signal_data_format_u", "uniongps__signal__data__format__u.html", "uniongps__signal__data__format__u" ],
    [ "intermediate_frequency_u", "unionintermediate__frequency__u.html", "unionintermediate__frequency__u" ],
    [ "milliseoncd_time_tick_u", "unionmilliseoncd__time__tick__u.html", "unionmilliseoncd__time__tick__u" ],
    [ "receiver_setting_s", "structreceiver__setting__s.html", "structreceiver__setting__s" ],
    [ "rtc_time_s", "structrtc__time__s.html", "structrtc__time__s" ],
    [ "rtc_time_u", "unionrtc__time__u.html", "unionrtc__time__u" ],
    [ "samples_per_ms_u", "unionsamples__per__ms__u.html", "unionsamples__per__ms__u" ],
    [ "sensors_s", "structsensors__s.html", "structsensors__s" ],
    [ "seoncd_time_tick_u", "unionseoncd__time__tick__u.html", "unionseoncd__time__tick__u" ],
    [ "signature_u", "unionsignature__u.html", "unionsignature__u" ],
    [ "time_measurement_s", "structtime__measurement__s.html", "structtime__measurement__s" ],
    [ "usb_frame_s", "structusb__frame__s.html", "structusb__frame__s" ],
    [ "usb_frame_u", "unionusb__frame__u.html", "unionusb__frame__u" ],
    [ "version_u", "unionversion__u.html", "unionversion__u" ]
];