/**
@file       sw_architecture.c

@brief      Documentation for CLEON software architecture

@page       SW_ARCH     Software architecture    

@section    SW_STRUCT   Software structure
                        - The software is fully interrupt-driven and the system remains in low-power-mode almost all the time
                        - Software is modularized into several sub-groups
                        - \b 'Sys' is for board-level abstraction and \b 'hal' is for hardware-level (mainly for MCU)\n
                          (\b cleon_conf.h (in 'platform') bridges 'sys' and 'hal') \n
                          (It means that it is possible to easily replace the MSP430F5338 with new MCU with minimum efforts by modifying 'hal' and 'cleon_conf.h' only) \n
                            @image html file_structure.jpg 
                            + \b app : application programming interface (API) for sensor data logging and USB connectivity
                            + \b doc : documentation (files in this group will be excluded from build)
                            + \b fs : FatFs file system (http://elm-chan.org/fsw/ff/00index_e.html)
                            + \b hal : hardware access layer (HAL) for MSP430F5338
                            + \b main : contains main.c
                            + \b platform : platform definition
                            + \b sys : system functions
                            + \b output : target file generated by compiler

@section    SW_FLOW     Software flowchart
                        - The flowchart below briefly shows software flow \n
                          (Note that this is simplified flow and there would be a little difference in real operation)
                          
                            @image html flowchart.jpg 

*/